=== yuanjianqi/simpleDbutilsandOrm/src/main/resources/sdao-config.dtd
<!ELEMENT sdao-config (datasource,show_sql?)>
<!ELEMENT datasource (base_property,base_property,base_property,base_property,property*)>
<!ATTLIST datasource type (jdbc|c3p0) #REQUIRED>
<!ELEMENT base_property EMPTY>
<!ATTLIST base_property name (driverClass|jdbcUrl|username|password) #REQUIRED>
<!ATTLIST base_property value CDATA #REQUIRED>
<!ELEMENT property EMPTY>
<!ATTLIST property name (initialPoolSize|minPoolSize|maxPoolSize|acquireIncrement|maxIdleTime|idleConnectionTestPeriod|acquireRetryAttempts|acquireRetryDelay) #REQUIRED>
<!ATTLIST property value CDATA #REQUIRED>
<!ELEMENT show_sql (#PCDATA)>

=== yuanjianqi/simpleDbutilsandOrm/src/main/resources/sdao-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sdao-config SYSTEM "sdao-config.dtd">
<sdao-config>
    <!-- 数据源配置-->
    <datasource type="c3p0">
        <!-- 基本参数配置-->
        <base_property name="driverClass" value=""/>
        <base_property name="jdbcUrl" value=""/>
        <base_property name="username" value=""/>
        <base_property name="password" value=""/>

        <!-- 可选项-->
        <!-- 连接池初始化时创建的连接数,default : 3，取值应在minPoolSize与maxPoolSize之间-->
        <property name="initialPoolSize" value=""/>
        <!-- 连接池保持的最小连接数,default : 3-->
        <property name="minPoolSize" value=""/>
        <!-- 连接池中拥有的最大连接数，如果获得新连接时会使连接总数超过这个值则不会再获取新连接，而是等待其他连接释放，所以这个值有可能会设计地很大,default : 15-->
        <property name="maxPoolSize" value=""/>
        <!--连接池在无空闲连接可用时一次性创建的新数据库连接数,default : 3-->
        <property name="acquireIncrement" value=""/>
        <!-- 连接的最大空闲时间，如果超过这个时间，某个数据库连接还没有被使用，则会断开掉这个连接。如果为0，则永远不会断开连接,即回收此连接。default : 0 单位 s-->
        <property name="maxIdleTime" value=""/>
        <!--每900秒检查所有连接池中的空闲连接 -->
        <property name="idleConnectionTestPeriod" value=""/>
        <!-- 连接池在获得新连接失败时重试的次数，如果小于等于0则无限重试直至连接获得成功。default : 30（建议使用）-->
        <property name="acquireRetryAttempts" value=""/>
        <!-- 两次连接中间隔时间，单位毫秒，连接池在获得新连接时的间隔时间。default : 1000 单位ms（建议使用）-->
        <property name="acquireRetryDelay" value=""/>
    </datasource>

    <!-- 策略配置-->
    <show_sql>true</show_sql>
</sdao-config>
